application: pitt-yak
version: v2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /cron/.*
  script: cronjobs.app
  login: admin

- url: /pictures
  static_dir: static/pictures

- url: /static
  static_dir: static

- url: /.*
  script: main.app
  


